package it.core.am;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '10035848' at '27/09/16 11.08' with Gradle 2.14.1
 *
 * @author 10035848, @date 27/09/16 11.08
 */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Library 
{
	public static void main(String[] args) {
        SpringApplication.run(Library.class, args);
    }

	public boolean someLibraryMethod() {
		
		return false;
	}
}
