/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '10035848' at '27/09/16 11.08' with Gradle 2.14.1
 *
 * @author 10035848, @date 27/09/16 11.08
 */
public class Library 
{
    public boolean someLibraryMethod() 
    {
    	
        return true;
    }
}
